next/next.config.js
Redirect based on most visited pages - [table](https://magistratba.sharepoint.com/:x:/s/InnovationTeam/EeJSKJCDQPRLp2mhShRyB4oBdtN_izUKycujtPgy70gc8g?e=znhTAe)
It would be nice to ignore the old query params, but it does not break anything if they are passed to new url.
(I was not able to match old url with query params as string event using `\\?`)
=> MD-148: update next config with redirects

next/components/atoms/ScrollToTopButton.tsx, next/components/atoms/TextField.tsx, next/components/layouts/BundleLayout.tsx, next/components/layouts/PageLayout.tsx, next/components/molecules/Cards/ServiceCard.tsx, next/components/molecules/FilteringSearchInput.tsx, next/components/molecules/Search.tsx, next/components/molecules/Section.tsx, next/components/molecules/SideBar.tsx, next/components/molecules/SideBarContact.tsx, next/components/sections/CardSection.tsx, next/components/sections/MapSection.tsx, next/pages/styleguide/index.tsx, next/styles/table.scss
[MD-332](https://inovaciebratislava.atlassian.net/browse/MD-332) - service cards mobile layout
[MD-331](https://inovaciebratislava.atlassian.net/browse/MD-331) - service cards - remove subtext
[MD-329](https://inovaciebratislava.atlassian.net/browse/MD-329) - sidebar grid layout - change breakpoint from `md` to `lg`
[MD-319](https://inovaciebratislava.atlassian.net/browse/MD-319) - search field - icon fix
[MD-314](https://inovaciebratislava.atlassian.net/browse/MD-314) - change font size in tables from small to medium
fix z index for MapSecion filters
=> minor fixes

next/components/atoms/Modal.tsx, next/components/molecules/Footer/Footer.tsx, next/components/molecules/ImageLightBox.tsx, next/components/molecules/Slider.tsx
\+ [MD-311](https://inovaciebratislava.atlassian.net/browse/MD-311) Footer map fix in Safari
\+ some typos corrected
=> MD-325: image caption in image gallery

next/components/molecules/ImageLightBox.tsx, next/components/molecules/Slider.tsx
react-aria's FocusScope has autoFocus feature but it's still not working in strict mode so this is the workaround...
=> MD-338 Add auto focus to image gallery

next/.env.bratiska-cli-build.dev, next/.env.bratiska-cli-build.prod, next/.env.bratiska-cli-build.staging, next/components/sections/MapSection.tsx, next/pages/pages/[...fullPath].tsx
- light style added
- error displaying fixed
=> MD-335 Map section fixes

next/components/molecules/BranchGroup.tsx, next/components/molecules/Row/Row.tsx, next/components/sections/OpeningHoursSection.tsx, next/graphql/index.ts, next/graphql/queries/components.gql, next/graphql/queries/entities.gql, next/pages/branches/[...fullPath].tsx, next/pages/pages/[...fullPath].tsx, strapi/src/api/branch/content-types/branch/schema.json, strapi/src/api/office/content-types/office/schema.json, strapi/src/api/office/controllers/office.ts, strapi/src/api/office/routes/office.ts, strapi/src/api/office/services/office.ts, strapi/src/api/page/content-types/page/schema.json, strapi/src/components/blocks/office-item.json, strapi/src/components/blocks/opening-hours-item.json, strapi/src/components/blocks/opening-hours-universal.json, strapi/src/components/sections/branch-group.json, strapi/src/components/sections/opening-hours-section.json
- opening hours in cemeteries are taken from general opening hours or from cemetery override
- branches have no opening hours
- branches have relation to offices (Pracoviská)
- offices have their opening hours
- new Opening hours section added - with relations to offices
=> MD0229: add branch offices with opening hours

next/.eslintrc.js, next/assets/map-marker.svg, next/components/atoms/Checkbox.tsx, next/components/atoms/Forms/FormCheckbox.tsx, next/components/atoms/Forms/FormRadioGroup.tsx, next/components/atoms/Forms/FormTextField.tsx, next/components/atoms/TextField.tsx, next/components/molecules/Accordion/AccordionItem.tsx, next/components/molecules/Search.tsx, next/components/sections/Application/ApplicationSection.tsx, next/components/sections/Application/ApplicationStep1.tsx, next/components/sections/Application/ApplicationStep2.tsx, next/components/sections/Application/ApplicationStep3.tsx, next/components/sections/Application/ApplicationStep4.tsx, next/components/sections/Application/ApplicationStep5.tsx, next/components/sections/Application/ApplicationStep6.tsx, next/components/sections/Application/ApplicationStep7.tsx, next/components/sections/Application/ApplicationSummary.tsx, next/components/sections/Application/application.types.ts, next/components/sections/Application/application.utils.ts, next/components/sections/Application/useApplicationStep.tsx, next/graphql/index.ts, next/graphql/queries/entities.gql, next/graphql/queries/queries.gql, next/package.json, next/pages/application/index.tsx, next/utils/useLeavePageConfirm.ts, next/yarn.lock, strapi/src/api/cemetery/content-types/cemetery/schema.json
=> Application

next/kubernetes/base/deployment.yml, next/kubernetes/base/secrets/cloudflare-turnstile.secret.dev.yml, next/kubernetes/base/secrets/cloudflare-turnstile.secret.prod.yml, next/kubernetes/base/secrets/cloudflare-turnstile.secret.staging.yml, strapi/kubernetes/base/deployment.yml, strapi/kubernetes/base/secrets/cloudflare-turnstile.secret.dev.yml, strapi/kubernetes/base/secrets/cloudflare-turnstile.secret.prod.yml, strapi/kubernetes/base/secrets/cloudflare-turnstile.secret.staging.yml
~Will merge right after the CI passes to check whether it appears in staging deployment - the secret itself is already visible and correct in Lens.~
Nevermind as there's an urelated build error - will leave up to @MarekBodingerBA to check & merge, ping me please once it's there and I'll recheck.
=> Add marianum-next-cloudflare-turnstile-secret to deployment

next/.env, next/.env.bratiska-cli-build.dev, next/.env.bratiska-cli-build.prod, next/.env.bratiska-cli-build.staging, next/Dockerfile, next/components/atoms/RichText.tsx, next/components/atoms/Seo.tsx, next/components/molecules/CeremoniesDebtors/CemeterySelect.tsx, next/components/sections/CeremoniesArchiveSection.tsx, next/components/sections/CeremoniesSection.tsx, next/components/sections/DebtorsSection.tsx, next/components/sections/DisclosuresSection.tsx, next/pages/articles/[...fullPath].tsx, next/pages/branches/[...fullPath].tsx, next/pages/bundles/[...fullPath].tsx, next/pages/cemeteries/[...fullPath].tsx, next/pages/documents/[...fullPath].tsx, next/pages/index.tsx, next/pages/pages/[...fullPath].tsx, next/services/fetchers/ceremoniesArchiveSectionFetcher.ts, next/services/fetchers/ceremoniesSectionFetcher.ts, next/services/fetchers/debtorsSectionFetcher.ts, next/services/fetchers/disclosuresSectionFetcher.ts, next/styles/table.scss, next/utils/useHorizontalScrollFade.ts, strapi/Dockerfile
=> Listings improvements

next/kubernetes/base/deployment.yml
* changed setting for `readinessProbe` to wait 5 seconds after start, and fail after 3 attempts every 10 seconds = 30 seconds
* added `livenessProbe` and setup to wait 10 seconds after start and fail after 3 attempts every 30 seconds = 90 seconds
=> feat: added livenessProbe to Next deployment

next/components/sections/MapSection.tsx
- Issue was only that react-map-gl css file wasn't imported
=> Fix for invisible map pins

.github/workflows/label.yml
Copied from other projects. No testing needed.
=> Add PR Labeler workflow

.gitignore, docker-compose.yml
Copied from other projects. No testing needed.
=> #429 Setup postgres volume in docker-compose

next/components/atoms/MImage.tsx, next/components/atoms/RichText.tsx, next/components/sections/HomepageSlider.tsx
=> #385 Disable custom image loader

.github/workflows/deploy.yml
This PR adds notifications about pipeline status to slack channel via providing slack bot token
⚠️ This should be merged after https://github.com/bratislava/github-actions/pull/34
=> slack notifications

next/components/molecules/Navigation/NavigationProvider/useGetFullPath.ts, next/graphql/index.ts, next/graphql/queries/components.gql, next/graphql/queries/entities.gql, next/graphql/queries/queries.gql, next/next.config.js, next/package.json, next/services/fetchers/managedObjectsFetcher.ts, strapi/schema.graphql, strapi/src/api/managed-object/content-types/managed-object/schema.json, strapi/src/api/managed-object/controllers/managed-object.ts, strapi/src/api/managed-object/routes/managed-object.ts, strapi/src/api/managed-object/services/managed-object.ts, strapi/src/api/page/content-types/page/schema.json, strapi/src/components/sections/map-of-managed-objects.json
- Create Strapi entities and components for a React component showing a map of managed objects
- Write queries to fetch the new data from Strapi and handle Next rewrites
=> #388 Map of objects in administration - groundwork

next/components/atoms/MImage.tsx, next/components/atoms/RichText.tsx, next/components/sections/HomepageSlider.tsx
Custom image loader was removed. For context, see the issue.
No testing needed, only unused code was removed.
Maybe run eslint and tsc.
=> Remove custom image loader

next/public/locales/en/common.json, next/public/locales/sk/common.json
Update text in SkipToContentButton to match other projects.
Second part of the task was already implemented:
Open homepage, press Tab once or twice, you should see a button in left upper corner with the correct text "Preskočiť navigáciu"
=> #378 Update text in SkipToContentButton

next/components/molecules/Navigation/NavigationProvider/useGetFullPath.ts
Update the hard-coded managedObjects path to reflect new requirements
=> #488 Update managedObjects path

next/pages/cemeteries/[...fullPath].tsx
Fix for use title from Strapi in Gallery
Try to setup Cemetery Gallery title in strapi and see its changes in web
=> Use title from Strapi in Gallery

next/next.config.js
- Update fullPath for managed objects route in `next.config.js`
- Test if detail pages for managed objects show properly
=> #488 Fix broken URLs for detail pages of managed objects

next/graphql/index.ts, strapi/types/generated/contentTypes.d.ts
Fix graphql index.ts file erros from #499
=> Fix graphql index.ts

next/pages/cemeteries/[...fullPath].tsx
Exchange location of video and documents in cemeteries
=> #494 Fix for video location in cemeteries

next/pages/pages/[...fullPath].tsx, next/utils/prefetchPageSections.ts
This is just a quick fix implementing prefetching for cemeteries.
In a separate PR, all prefetching will be implemented properly.
At http://localhost:3000/o-nas/cintoriny-v-sprave, the map should initially load with correct zoom & position, so all cemeteries are included in the bounding box.
=> Implement react-query prefetching for cemeteries only to fix cemetery map

strapi/patches/@strapi+admin+4.25.22.patch
Add patch @strapi/admin fix so the caption and alt text doesn't show null when they are empty
Add image from image gallery in Strapi without caption and alt text and no null should be shown
There seems to be Hydration error when images are loaded in next, seems that issue is not related to the current changes
=> #537 Fix caption null in @strapi/admin patch

next/components/atoms/Tabs/Tabs.tsx
Added a dependency to useEffect in Tabs.
Check that pressing homepage procedure tabs on mobile devices works correctly.
=> #588 Fix tabs press behavior

README.md, next/components/sections/IframeSection.tsx, next/package-lock.json, next/package.json, strapi/types/generated/contentTypes.d.ts
Add library for resize iframe.
=> #619 Add iframe resize library
